### ISSUE TITLE
实际判断获取不到IP地址？

### ISSUE THREAD

**Issue by peasoft** [vvmcat/Github-SpeedUpTool#1]
使用“实际判断”加速时，经常出现无法识别到IP的问题，造成Hosts里很多条域名前是没有IP的。

另外，界面上的 `RawGithubusercontent` 是什么意思，是勾选后加速 raw.githubusercontent.com，不勾选不加速吗？

**Comment by vvmcat** [comment]
“实际判断”是调用的 ip-api.com 的地址对 Github 域名进行解析出IP，如果无法使用建议改用“直接转换”
界面上的 RawGithubusercontent 为：勾选后会加速 raw.githubusercontent.com 这个域名地址，可以解决部分 Raw 访问显示找不到 IP 服务器的问题 （勾选后加速 raw.githubusercontent.com，不勾选不加速）

**Comment by vvmcat** [comment]
“实际判断”是调用的 ip-api.com 的地址对 Github 域名进行解析出IP，如果无法使用建议改用“直接转换”
界面上的 RawGithubusercontent 为：勾选后会加速 raw.githubusercontent.com 这个域名地址，可以解决部分 Raw 访问显示找不到 IP 服务器的问题 （勾选后加速 raw.githubusercontent.com，不勾选不加速）
